### ISSUE TITLE
Please Compatible with React-native >=0.40

### ISSUE THREAD

**Issue by WangZiXiao-ChenDu** [lunarmayor/react-native-open-settings#6]

**Comment by sfratini** [comment]
If you are talking about the compiling error, just remove the @Override here:

```
@Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
```

in the OpenSeettingsPackage.java file.

**Comment by sfratini** [comment]
@lunarmayor Although it is quite easy to fix this, it is a manual task every time the project is installed. Could you please update the project with this change? That would be so much easier.
